# Generated by Django 3.2 on 2023-03-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=3),
        ),
    ]
